from recommenders.hybrid_base import Hybrid


class HybridSimilarity(Hybrid):

    def __init__(self, similarity_matrices_array, normalization_mode, mode, cluster, weights_array, urm_name):
        name = 'HybridSimilarity'

        #TODO AUTOGENERATED
        #self.INVERSE = False

        #if similarity_matrices_array[0].shape[0] == data.N_PLAYLISTS:
        #    self.INVERSE = True

        super(HybridSimilarity, self).__init__(name=name, mode=mode, cluster=cluster,
                                               matrices_array=similarity_matrices_array,
                                               normalization_mode=normalization_mode,
                                               weights_array=weights_array)
        self.urm_name = urm_name
